name: Build and Upload to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    name: Build and Upload to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: player/package-lock.json

      - name: Install Dependencies
        working-directory: ./player
        run: npm install --legacy-peer-deps

      - name: Build Project
        working-directory: ./player
        run: |
          npm run build-npm-package
          ls -la
          cd ./www/preview
          ls -la


    #   - name: Authenticate and Upload to Google Cloud Storage
    #     if: env.CLOUD_PROVIDER == 'gcp'
    #     run: |
    #         echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 -d > /tmp/service-account-key.json
    #         gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
    #         gsutil -m cp -r player/www/* gs://${{ env.GCP_BUCKET }}/v3/
    #         rm -f /tmp/service-account-key.json
